### ISSUE TITLE
Cannot comment nested multiline comments

### ISSUE THREAD

**Issue by Danny-Conecta-Entradas** [8rin5x/oneLineComments#2]
This extension is really great and I'll for sure will use it a lot,
but I encounter this problem whil trying

In CSS, if you have a rule like this
```css
.selector {
  /*
    Neted multiline comment 
  */

  background-color: #fff;
}
```

When you try to comment it shows you a warning
```
⚠️ Unbalanced delimiter found in string
````

But if the comment is single line it works as expected.

Same thing happens in HTML.

```html
<div></div>
<!--
      Nested multiline comment
-->
<div></div>
```

I really hope this can be solved.
